class ConnectionError(Exception):
    """Error context here

    Attributes:
        attr -- attr desc
    """

    def __init__(self):
      pass